### PR TITLE
fix: Fix build issues

### PR DESCRIPTION
**Pull request by KIRA009**
**What kind of change does this PR introduce?**
Addresses #901 

**Summary**
- [x] This largely addresses the app failing to run as found in #901.
- [ ] It also fixes the windows build

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have performed a self-review of my code
* [x] If applicable, I have added tests to prove my fix is functional/effective
* [x] I have linted my code locally prior to submission
* [x] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [x] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**
Build the app and run it

**Other information**

### CODE REVIEW

**Comment by abrichr** [comment]
@KIRA009 can I merge this?

**Comment by KIRA009** [comment]
> @KIRA009 thank you! 🙏 
> 
> Is this ready to merge?

I am fixing the build as well in this PR

**Comment by KIRA009** [comment]
@abrichr This is now ready

**Review by abrichr — APPROVED** [review]
LGTM!

**Pull request merged**
