### PR TITLE
chore: modify install script to execute on user's repo and branch

### PR DESCRIPTION
**Pull request by Mustaballer**
**What kind of change does this PR introduce?**

Updates `install\install_openadapt.sh` so it executes `pytest` testing on the user's current branch. This works for forked repos as well. 

**Summary**

This way the github action script will always run `pytest` on the current branch and not on the main branch as it is currently.

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have performed a self-review of my code
* [x] If applicable, I have added tests to prove my fix is functional/effective
* [x] I have linted my code locally prior to submission
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [x] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**

**Other information**

### CODE REVIEW

**Comment by Mustaballer** [comment]
@abrichr Ready for Review!

**Comment by Mustaballer** [comment]
I tested this script on my forked repo, and it does successfully clone the correct repo and check out the branch. This should be ready for merging :)
image
image

**Comment by abrichr** [comment]
@Mustaballer should I enable this? 
image

**Comment by Mustaballer** [comment]
> @Mustaballer should we enable any of these?
> 
> image image

@abrichr I think we should enable the first two checkmarks so PR maintain high consistancy. Regarding deployments we currently don't use any so its not necessary. We do need to add the status check in the search bar which I can add.

**Comment by Mustaballer** [comment]
@abrichr I added the status check rule, so status checks must pass for PRs to be merged. Note, the 🟤 brown progress circle was automatically added to all PRs that currently don't have a ✔️  or ❌ mark(PRs that have not run the status checks since they were enabled). 
image

Once the user makes a new commit, it will run the status check and give an ✔️ or ❌  mark if it passed or failed.

This PR is ready for merging :)

**Comment by Mustaballer** [comment]
@abrichr Ready for merging :)

**Comment by abrichr** [comment]
@Mustaballer can you please configure the permissions discussed above? 🙏

**Review by abrichr — APPROVED** [review]
LGTM!

**Pull request merged**
