### PR TITLE
Gisting

### PR DESCRIPTION
**Pull request by FFFiend**
Addresses #27 , please run ```gist_test.py``` using Modal to view OOM error.

I've highlighted this in the actual docstring, however you can go into the ```compress.py``` file inside where you installed the module (lines 105-107, device_map="auto" and nn.Parallel(..)) , and observe how I've tried enabling multi GPU usage, to no avail :(

### CODE REVIEW

**Comment by FFFiend** [comment]
Ready for review @abrichr or rather investigation, because it refuses to run in parallel across the GPU's.

**Comment by abrichr** [comment]
Thanks @FFFiend ! Can you please clarify where `gisting_test` is defined? Ideally we would also have a script to deploy this automatically.

**Comment by abrichr** [comment]
Please add links to all of your conversations with third parties here 🙏

**Comment by abrichr** [comment]
Please spec out an AWS instance that would run Gisting 🙏

**Comment by abrichr** [comment]
@FFFiend can you please suggest the minimum required specifications for an AWS instance we can deploy to run this?

**Comment by FFFiend** [comment]
According to the comment here https://github.com/jayelm/gisting/issues/4, it should be possible to run on a single A100 40 GB GPU but given that that's not the case, the absolute minimum I can think of is 2 A100 40GB GPU's, or perhaps just one singular 80 GB GPU if that's available. This would require a one line modification in ```compress.py```'s code though, and that is adding ```device_map="auto"``` into the model initializer.

**Comment by abrichr** [comment]
Moved to https://github.com/OpenAdaptAI/OpenAdapt/pull/395/files

**Pull request closed without merging**
