### PR TITLE
Implemented model cursor for visual feedback #760

### PR DESCRIPTION
**Pull request by Subh231004**
Implemented model cursor for visual feedback
/claim #760 

**What kind of change does this PR introduce?**

**Summary**

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have performed a self-review of my code
* [x] If applicable, I have added tests to prove my fix is functional/effective
* [x] I have linted my code locally prior to submission
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [x] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**

**Other information**

### CODE REVIEW

**Comment by abrichr** [comment]
Good start! It might be easier to copy and paste the contents of vanilla.py and start from there. It's not clear to me what is the right abstraction for strategies that build on it.

**Comment by abrichr** [comment]
I think probably we want to use a methodology similar to `VisualReplayStrategy` (i.e. segmentation + description) to generate initial cursor target candidates, then use the model cursor feedback to let it self-correct.

**Comment by Subh231004** [comment]
@abrichr I've made some changes in the files please review them and let me know if something more needs to be done

**Comment by abrichr** [comment]
@Subh231004 your code is unfortunately quite disorganized and difficult to read. I have enabled a build so that you can see the errors that will be reported by our style checkers. Please address those and I will be happy to take a closer look.

**Comment by Subh231004** [comment]
@abrichr can u please review the code I've tried to make it readable

**Comment by ayewo** [comment]
@abrichr 

Just a quick FYI that similar low-effort PRs have been opened in other projects[^1][^2] that end up getting closed. 

I only noticed because I got quite a few nonsensical GitHub notifications from `Subh231004` here[^3]  that have since been deleted by the maintainers.

[^1]: https://github.com/langchain4j/langchain4j/pull/1316
[^2]: https://github.com/gyroflow/gyroflow/pull/847
[^3]: https://github.com/langchain4j/langchain4j/issues/1132

**Comment by Subh231004** [comment]
I'm a beginner to the open source world and I'm trying hard to get to the
problem statements
I've had a short conversation with the maintainer of OpenAdapt and I have
his permission to work on it
I am just following whatever he is suggesting me

**Comment by ayewo** [comment]
> I'm a beginner to the open source world and I'm trying hard to get to the problem statements I've had a short conversation with the maintainer of OpenAdapt and I have his permission to work on it I am just following whatever he is suggesting me

@Subh231004 I totally get that. I was merely commenting so Richard could calibrate his expectations accordingly.

**Comment by abrichr** [comment]
Thank you @ayewo .

@Subh231004 thank you for your efforts. I appreciate your desire to contribute and I encourage you to continue. However this code is unfortunately not reviewable in its current state.

I suggest you try a simpler problem before attempting this one.

**Pull request closed without merging**
