### PR TITLE
Native Chrome Extension

### PR DESCRIPTION
**Pull request by KrishPatel13**
I have made the manifest and the native-manifest.json files.

Also I have installed the native-messaging python package.

I am getting this error on unpacking the browser.py on the Chrome Extension Store.

image

The Reason I had to split the background.py and content.py is that, 

```
let observer = new MutationObserver(mutations => {
    for(let mutation of mutations) {
        browser.runtime.sendNativeMessage("puterbot", mutation).then(onReceived);
    }
});
```

MutationObserver was not supported by the nativemessaging. So it was giving an error.

### CODE REVIEW

**Comment by abrichr** [comment]
@KrishPatel13 great work! Can you please expand the errors and copy the text here?

**Comment by KrishPatel13** [comment]
Thank you @abrichr !

But unfortunately, there is no context to the error on the extension page.

This is how it looks:
image
image

**Comment by abrichr** [comment]
@KrishPatel13 thank you. See here for debugging Chrome extensions: https://developer.chrome.com/docs/extensions/mv3/tut_debugging/

**Comment by KrishPatel13** [comment]
https://github.com/MLDSAI/OpenAdapt/issues/51#issuecomment-1580869647

**Comment by KrishPatel13** [comment]
test

**Pull request closed without merging**
