### PR TITLE
feat(chrome_extension): Add DOM changes to Database (Pipe -> Write)

### PR DESCRIPTION
**Pull request by KrishPatel13**
Add DOM changes to Database (Pipe -> Write)
**What kind of change does this PR introduce?**
This PR has the Chrome Extension Working which logs document's Outer HTML and Inner HTML.

**Summary**

**Checklist**
* [ ] My code follows the style guidelines of OpenAdapt
* [ ] I have performed a self-review of my code
* [ ] If applicable, I have added tests to prove my fix is functional/effective
* [ ] I have linted my code locally prior to submission
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [ ] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**

**Other information**

### CODE REVIEW

**Comment by KrishPatel13** [comment]
Some Notes regarding Chrome Extension: _https://docs.google.com/presentation/d/106AXW3sBe7-7E-zIggnMnaUKUXWAj_aAuSxBspTDcGk/edit?usp=sharing_

**Comment by KrishPatel13** [comment]
Blocker Error in backgroud.js service-worker console: 
image

**Comment by KrishPatel13** [comment]
I have tested the namepipe library in different ways:

1. try bidirectional (duplex) binary pipe (simulatneuosly writing and reading)
image

From this I learnt that, it needs to use open (<piep.path>) got the client (pong.py) to get the access to the pipe.

2. Try ping.py for 'wt' and pong.py 'rt': (both use  NPopen)
This time in pong.py it gives the following error:
```
    self._pipe = win32pipe.CreateNamedPipe(
pywintypes.error: (5, 'CreateNamedPipe', 'Access is denied.')
```

This means that ping can NOT access the pipe when the other process is using.

**Comment by KrishPatel13** [comment]
Update: resolved using sockets

**Comment by abrichr** [comment]
Closed in favor of https://github.com/OpenAdaptAI/OpenAdapt/pull/364

**Pull request closed without merging**
